### ISSUE TITLE
Response writing before request's body reading

### ISSUE THREAD

**Issue by dstdfx** [selectel/go-selvpcclient#120]
It's possible to get "_http: invalid Read on closed Body_" error [here](https://github.com/selectel/go-selvpcclient/blob/master/selvpcclient/testutils/handlers.go#L65) and face [the known issue](https://github.com/golang/go/issues/15527) cuz response is being written before request body is read.

**Comment by ozerovandrei** [comment]
Fixed in #121, thanks @dstdfx
